In [1]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('datasets/Shopping/train.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
df.shape

(3900, 19)

In [8]:
for col in df.columns:
    print(f'{col}: {df[col].unique()}')

Customer ID: [   1    2    3 ... 3898 3899 3900]
Age: [55 19 50 21 45 46 63 27 26 57 53 30 61 65 64 25 52 66 31 56 18 38 54 33
 36 35 29 70 69 67 20 39 42 68 49 59 47 40 41 48 22 24 44 37 58 32 62 51
 28 43 34 23 60]
Gender: ['Male' 'Female']
Item Purchased: ['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']
Category: ['Clothing' 'Footwear' 'Outerwear' 'Accessories']
Purchase Amount (USD): [ 53  64  73  90  49  20  85  34  97  31  68  72  51  81  36  38  48  62
  37  88  22  25  56  94  79  67  91  33  69  45  60  76  39 100  21  43
  54  55  30  28  59  24  83  46  70  29  26  58  96  40  32  95  41  47
  99  87  92  98  89  35  75  65  86  84  77  27  23  74  80  42  61  82
  78  93  50  57  66  44  52  71  63]
Location: ['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Maryland' 'Vermont'
 'New Mexico' 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah'
 'Virginia' 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota'
 'Washington' 'Wisconsin' 'Michigan']
Size: ['L' 'S' 'M' 'XL']
Color: ['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold' 'Violet' 'Teal' 'Lavender' 'Black' 'Green' 'Peach' 'Red'
 'Cyan' 'Brown' 'Beige' 'Orange' 'Indigo' 'Yellow' 'Magenta' 'Blue']
Season: ['Winter' 'Spring' 'Summer' 'Fall']
Review Rating: [3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5 4.7 2.8 4.6 3.3 4.4 3.6 5.  4.
 3.7 4.2 3.9 3.  3.8 3.4 4.3 2.5]
Subscription Status: ['Yes' 'No']
Payment Method: ['Credit Card' 'Bank Transfer' 'Cash' 'PayPal' 'Venmo' 'Debit Card']
Shipping Type: ['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']
Discount Applied: ['Yes' 'No']
Promo Code Used: ['Yes' 'No']
Previous Purchases: [14  2 23 49 31 19  8  4 26 10 37 34 44 36 17 46 50 22 32 40 16 13  7 41
 45 38 48 18 15 25 39 35 29 21 43  3  5 24 42 47 28 20 33  1  9 12 27 11
 30  6]
Preferred Payment Method: ['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']
Frequency of Purchases: ['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

In [2]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [24]:
df = pd.read_csv('logs/data/df_for_experiments.csv')

In [25]:
df.isna().sum()

Unnamed: 0                   0
Pclass                       0
Age                        177
SibSp                        0
Parch                        0
                          ...
large_family_fare_pca        0
teen_female_embarked         2
age_log_fare_pca           177
teen_female_fare_scaled      0
Survived                     0
Length: 210, dtype: int64

In [28]:
with pd.option_context('display.max_rows', None):
    print(df.fillna(df.median()).isna().sum())

Unnamed: 0                          0
Pclass                              0
Age                                 0
SibSp                               0
Parch                               0
Fare                                0
freq_encoded_Pclass                 0
freq_encoded_Sex                    0
ordinal_encoded_Embarked            0
onehot_Embarked_S                   0
onehot_Embarked_C                   0
onehot_Embarked_Q                   0
freq_encoded_Title                  0
binary_encoded_Sex_male             0
binary_encoded_Sex_female           0
binary_Age_missing                  0
binary_Cabin_missing                0
binary_Child                        0
binary_Senior                       0
binary_high_fare                    0
binary_low_fare                     0
binary_Single                       0
binary_Large_family                 0
binary_Small_family                 0
freq_encoded_Ticket                 0
binary_Rare_Ticket                  0
binary_Family_Size_2                0
binary_Family_Size_3                0
binary_Title_Mr                     0
binary_Title_Mrs                    0
binary_Title_Miss                   0
binary_Title_Master                 0
binary_Title_Mlle                   0
binary_Title_Ms                     0
binary_Title_Mme                    0
onehot_Pclass_1                     0
onehot_Pclass_2                     0
onehot_Pclass_3                     0
binary_Embarked_missing             0
freq_encoded_Family_Size            0
ordinal_encoded_Title               0
name_token_count                    0
name_char_count                     0
name_avg_word_len                   0
ticket_digit_count                  0
ticket_letter_count                 0
ticket_length                       0
ticket_first_digit                  0
cabin_known                         0
Age_Scaled                          0
Fare_Log                            0
Age_Squared                         0
Fare_Squared                        0
Parch_Scaled                        0
Age_Log                             0
Age_SquareRoot                      0
SibSp_Log                           0
Parch_Log                           0
Fare_SquareRoot                     0
Age_Cubed                           0
Fare_Cubed                          0
SibSp_Cubed                         0
Parch_Cubed                         0
Pclass_Cubed                        0
Age_Exponential                     0
Fare_Exponential                  891
SibSp_Exponential                   0
Parch_Exponential                   0
Age_Reciprocal                      0
Fare_Reciprocal                     0
SibSp_Reciprocal                    0
Parch_Reciprocal                    0
Age_Binarized                       0
Fare_Binarized                      0
SibSp_Binarized                     0
Parch_Binarized                     0
Age_Negative                        0
Fare_Negative                       0
SibSp_Negative                      0
Parch_Negative                      0
Age_Shifted_1                       0
Fare_Shifted_1                      0
SibSp_Shifted_1                     0
Parch_Shifted_1                     0
Age_Diff                            0
Fare_Diff                           0
Age_Moving_Average_3                0
Fare_Moving_Average_3               0
SibSp_Moving_Average_3              0
Parch_Moving_Average_3              0
Age_Normalized                      0
Fare_Normalized                     0
SibSp_Normalized                    0
Parch_Normalized                    0
Age_CubedRoot                       0
imputed_age_median                  0
imputed_age_mean                    0
age_standard_scaled                 0
log_fare                            0
age_bin                             0
fare_bin                            0
family_size                         0
fare_normalized                     0
age_normalized                      0
sibsp_scaled                        0
parch_scaled                        0
age_clipped                         0
fare_clipped                        0
title                               0
is_child                            0
is_teenager                         0
is_adult                            0
fare_pclass_mean                    0
ticket_length_scaled                0
name_length_scaled                  0
family_size_normalized              0
fare_per_person                     0
fare_per_person_scaled              0
age_fare_ratio                      0
less_than_median_fare               0
teenage_female                      0
age_mean_without_na                 0
is_ticket_number                    0
ticket_numerical_length             0
mean_ticket_length                  0
deck_level                          0
ticket_num_length                   0
Pclass_PCA_1                        0
Age_PCA_1                           0
SibSp_PCA_1                         0
Parch_PCA_1                         0
Fare_PCA_1                          0
Cabin_PCA_1                         0
Age_Binned                          0
Fare_Square                         0
Fare_Cube                           0
Fare_Sqrt                           0
Fare_PCA_Square                     0
Fare_PCA_Cube                       0
Fare_PCA_Sqrt                       0
Ticket_Letter_Count_Square          0
Ticket_Letter_Count_Cube            0
Ticket_Letter_Count_Sqrt            0
Parch_Square                        0
Parch_Sqrt                          0
Fare_Per_Person_Square              0
Fare_Per_Person_Cube                0
Fare_Per_Person_Sqrt                0
SibSp_Binarized_and_Child           0
Large_Family_and_Child              0
Low_Fare_and_Child                  0
Fare_Per_Person_High_Variance       0
Age_Child_Interaction               0
Age_Title_Miss_Interaction          0
Embarked_and_Child                  0
Fare_Low_Fare_Interaction           0
Fare_Title_Miss_Interaction         0
Age_Log_Scale                       0
Age_is_Teenage_Female               0
Age_Normalized_Log                  0
SibSp_Binary_and_Large              0
Embarked_Q_and_LowFare              0
Embarked_Q_and_Child                0
Ticket_Letters_Scaled               0
Fare_PCA1_Normalized                0
Fare_PCA1_Log                       0
Age_and_Large_Family                0
SibSp_and_Embarked_Q                0
Age_Normalized_Binary_Child         0
Fare_Log_Title_Miss                 0
Parch_Title_Miss                    0
FamilySize_Normalized               0
Age_and_Fare                        0
Age_and_Ticket_Letter_Count         0
Low_Fare_and_Embarked               0
Age_and_Fare_PCA1                   0
age_per_person                      0
age_fare_per_person                 0
fare_per_person_reciprocal          0
parch_fare_person                   0
sibsp_fare_person                   0
child_family_ratio                  0
fare_age_ratio                      0
normalized_fare_age_reciprocal      0
ticket_family_ratio                 0
age_reciprocal_squared              0
fare_plus_age                       0
age_log_fare_normalized             0
sibsp_age                           0
large_family_parch                  0
fare_minus_age                      0
mean_age_fare                       0
large_family_fare                   0
child_fare_person                   0
lowfare_sibsp                       0
lowfare_parch                       0
fare_scaled_age                     0
age_plus_reciprocal                 0
embarked_parch                      0
age_fare_per_person_scaled          0
binary_child_mean_age               0
embarked_fare_normalized            0
titlemiss_fare_pca                  0
lowfare_ticket_letter_count         0
teenage_female_with_age_log         0
large_family_fare_pca               0
teen_female_embarked                0
age_log_fare_pca                    0
teen_female_fare_scaled             0
Survived                            0
dtype: int64

In [22]:
df.drop(['Unnamed: 0', 'Survived'], axis = 1)

,Pclass,Age,SibSp,Parch,Fare,freq_encoded_Pclass,freq_encoded_Sex,ordinal_encoded_Embarked,onehot_Embarked_S,onehot_Embarked_C,...,age_fare_per_person_scaled,binary_child_mean_age,embarked_fare_normalized,titlemiss_fare_pca,lowfare_ticket_letter_count,teenage_female_with_age_log,large_family_fare_pca,teen_female_embarked,age_log_fare_pca,teen_female_fare_scaled
0,0.827377,-0.530377,0.432793,-0.473674,-0.502445,0.900116,0.737695,-0.569684,0.619306,-0.482043,...,-0.356186,-0.381109,-0.314795,-0.078614,1.062457,-0.252973,-0.119820,-0.205174,-0.484784,-0.006844
1,-1.566107,0.571831,0.432793,-0.473674,0.786845,-1.003022,-1.355574,1.003139,-1.614710,2.074505,...,0.368340,-0.381109,0.895837,-0.078614,-0.160604,-0.252973,-0.119820,-0.205174,0.724288,-0.006844
2,0.827377,-0.254825,-0.474545,-0.473674,-0.488854,0.900116,-1.355574,-0.569684,0.619306,-0.482043,...,-0.320842,-0.381109,-0.306870,-0.884585,-0.160604,-0.252973,-0.119820,-0.205174,-0.494485,-0.006844
3,-1.566107,0.365167,0.432793,-0.473674,0.420730,-1.003022,-1.355574,-0.569684,0.619306,-0.482043,...,0.091418,-0.381109,0.223525,-0.078614,-0.160604,-0.252973,-0.119820,-0.205174,0.351385,-0.006844
4,0.827377,0.365167,-0.474545,-0.473674,-0.486337,0.900116,0.737695,-0.569684,0.619306,-0.482043,...,-0.399320,-0.381109,-0.305403,-0.078614,-0.160604,-0.252973,-0.119820,-0.205174,-0.530181,-0.006844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-0.369365,-0.185937,-0.474545,-0.473674,-0.386671,-1.224478,0.737695,-0.569684,0.619306,-0.482043,...,-0.226079,-0.381109,-0.247285,-0.078614,-0.160604,-0.252973,-0.119820,-0.205174,-0.406961,-0.006844
887,-1.566107,-0.737041,-0.474545,-0.473674,-0.044381,-1.003022,-1.355574,-0.569684,0.619306,-0.482043,...,0.060656,-0.381109,-0.047690,-0.151785,-0.160604,4.127288,-0.119820,2.517213,-0.093575,1.779093
888,0.827377,NaN,0.432793,2.008933,-0.176263,0.900116,-1.355574,-0.569684,0.619306,-0.482043,...,NaN,-0.381109,-0.124593,-0.369218,-0.160604,NaN,-0.530732,-0.205174,NaN,-0.006844
889,-1.566107,-0.254825,-0.474545,-0.473674,-0.044381,-1.003022,0.737695,1.003139,-1.614710,2.074505,...,0.114152,-0.381109,-0.073569,-0.078614,-0.160604,-0.252973,-0.119820,-0.205174,-0.097187,-0.006844
890,0.827377,0.158503,-0.474545,-0.473674,-0.492378,0.900116,0.737695,2.575963,-1.614710,-0.482043,...,-0.379615,-0.381109,-0.883154,-0.078614,-0.160604,-0.252973,-0.119820,-0.205174,-0.524432,-0.006844

In [23]:
df.fillna(df.median()).isna().sum()

Unnamed: 0                 0
Pclass                     0
Age                        0
SibSp                      0
Parch                      0
                          ..
large_family_fare_pca      0
teen_female_embarked       0
age_log_fare_pca           0
teen_female_fare_scaled    0
Survived                   0
Length: 210, dtype: int64

In [19]:
df.columns

Index(['Unnamed: 0', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'freq_encoded_Pclass', 'freq_encoded_Sex', 'ordinal_encoded_Embarked',
       'onehot_Embarked_S',
       ...
       'binary_child_mean_age', 'embarked_fare_normalized',
       'titlemiss_fare_pca', 'lowfare_ticket_letter_count',
       'teenage_female_with_age_log', 'large_family_fare_pca',
       'teen_female_embarked', 'age_log_fare_pca', 'teen_female_fare_scaled',
       'Survived'],
      dtype='object', length=210)

In [14]:
df.fillna()

Empty DataFrame
Columns: [Unnamed: 0, Pclass, Age, SibSp, Parch, Fare, freq_encoded_Pclass, freq_encoded_Sex, ordinal_encoded_Embarked, onehot_Embarked_S, onehot_Embarked_C, onehot_Embarked_Q, freq_encoded_Title, binary_encoded_Sex_male, binary_encoded_Sex_female, binary_Age_missing, binary_Cabin_missing, binary_Child, binary_Senior, binary_high_fare, binary_low_fare, binary_Single, binary_Large_family, binary_Small_family, freq_encoded_Ticket, binary_Rare_Ticket, binary_Family_Size_2, binary_Family_Size_3, binary_Title_Mr, binary_Title_Mrs, binary_Title_Miss, binary_Title_Master, binary_Title_Mlle, binary_Title_Ms, binary_Title_Mme, onehot_Pclass_1, onehot_Pclass_2, onehot_Pclass_3, binary_Embarked_missing, freq_encoded_Family_Size, ordinal_encoded_Title, name_token_count, name_char_count, name_avg_word_len, ticket_digit_count, ticket_letter_count, ticket_length, ticket_first_digit, cabin_known, Age_Scaled, Fare_Log, Age_Squared, Fare_Squared, Parch_Scaled, Age_Log, Age_SquareRoot, SibSp_Log, Parch_Log, Fare_SquareRoot, Age_Cubed, Fare_Cubed, SibSp_Cubed, Parch_Cubed, Pclass_Cubed, Age_Exponential, Fare_Exponential, SibSp_Exponential, Parch_Exponential, Age_Reciprocal, Fare_Reciprocal, SibSp_Reciprocal, Parch_Reciprocal, Age_Binarized, Fare_Binarized, SibSp_Binarized, Parch_Binarized, Age_Negative, Fare_Negative, SibSp_Negative, Parch_Negative, Age_Shifted_1, Fare_Shifted_1, SibSp_Shifted_1, Parch_Shifted_1, Age_Diff, Fare_Diff, Age_Moving_Average_3, Fare_Moving_Average_3, SibSp_Moving_Average_3, Parch_Moving_Average_3, Age_Normalized, Fare_Normalized, SibSp_Normalized, Parch_Normalized, Age_CubedRoot, imputed_age_median, imputed_age_mean, age_standard_scaled, log_fare, age_bin, ...]
Index: []

[0 rows x 210 columns]

In [12]:

df = pd.read_csv('../datasets/Titanic/train.csv')

In [17]:
df.columns

Index(['Unnamed: 0', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'freq_encoded_Pclass', 'freq_encoded_Sex', 'ordinal_encoded_Embarked',
       'onehot_Embarked_S',
       ...
       'binary_child_mean_age', 'embarked_fare_normalized',
       'titlemiss_fare_pca', 'lowfare_ticket_letter_count',
       'teenage_female_with_age_log', 'large_family_fare_pca',
       'teen_female_embarked', 'age_log_fare_pca', 'teen_female_fare_scaled',
       'Survived'],
      dtype='object', length=210)

In [15]:
df_filled = df.fillna(df.median())

In [16]:
df_filled.isna().sum()

Unnamed: 0                 0
Pclass                     0
Age                        0
SibSp                      0
Parch                      0
                          ..
large_family_fare_pca      0
teen_female_embarked       0
age_log_fare_pca           0
teen_female_fare_scaled    0
Survived                   0
Length: 210, dtype: int64

In [13]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df = df._get_numeric_data()

In [10]:
pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

     PassengerId  Survived    Pclass       Age     SibSp     Parch      Fare
0      -1.730108 -0.789272  0.827377 -0.530377  0.432793 -0.473674 -0.502445
1      -1.726220  1.266990 -1.566107  0.571831  0.432793 -0.473674  0.786845
2      -1.722332  1.266990  0.827377 -0.254825 -0.474545 -0.473674 -0.488854
3      -1.718444  1.266990 -1.566107  0.365167  0.432793 -0.473674  0.420730
4      -1.714556 -0.789272  0.827377  0.365167 -0.474545 -0.473674 -0.486337
..           ...       ...       ...       ...       ...       ...       ...
886     1.714556 -0.789272 -0.369365 -0.185937 -0.474545 -0.473674 -0.386671
887     1.718444  1.266990 -1.566107 -0.737041 -0.474545 -0.473674 -0.044381
888     1.722332 -0.789272  0.827377       NaN  0.432793  2.008933 -0.176263
889     1.726220  1.266990 -1.566107 -0.254825 -0.474545 -0.473674 -0.044381
890     1.730108 -0.789272  0.827377  0.158503 -0.474545 -0.473674 -0.492378

[891 rows x 7 columns]

In [11]:
cars = pd.read_csv('../datasets/Cars/train.csv')

In [12]:
cars.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [14]:
cars.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [1]:
d = {1:0.1, 2:33, 4:-0.5}

In [2]:
[k for k,v in d.items() if v > 0]

[1, 2]

In [4]:
# Example DataFrame
import pandas as pd
data = {
    'A': [1, 2, 3],
    'B': [1, 2, 3],  # This column is a duplicate of 'A'
    'C': [4, 5, 6],
    'D': [4, 5, 6]   # This column is a duplicate of 'C'
}

df = pd.DataFrame(data)

# Transpose the DataFrame, drop duplicates, then transpose it back to the original shape
df_cleaned = df.T.drop_duplicates().T

print(df_cleaned)

   A  C
0  1  4
1  2  5
2  3  6

In [9]:
import sklearn
from sklearn.datasets import load_diabetes
import pandas as pd

In [10]:
diabetes = load_diabetes(scaled=False, as_frame=True)

In [15]:
df = diabetes.data
df['target'] = diabetes.target

In [18]:
df.to_csv('diabetes.csv', index_label=False)

In [3]:
def hyp_res_to_text(hypothesis_results):
    res = ''
    for tup in hypothesis_results:
        tmp = tup[0]+': ' + str(bool(tup[1]))
        res += (tmp + '\n')
    return res

In [5]:
t = [('aaa',1), ('bbb',0)]
print(hyp_res_to_text(t))

aaa: True
bbb: False

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

def split_and_save_dataset(dataset_name):
    """
    Splits the dataset into training and testing sets and saves them as CSV files.
    
    Args:
        dataset_name (str): The name of the dataset file (CSV format).
    """
    try:
        # Load the dataset
        df = pd.read_csv(dataset_name)
        print(f"Dataset loaded successfully with shape: {df.shape}")

        # Split the dataset into 80% train and 20% test
        train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
        print(f"Train set shape: {train_df.shape}, Test set shape: {test_df.shape}")

        # Save the dataframes as CSV files
        train_df.to_csv("train.csv", index=False)
        test_df.to_csv("test.csv", index=False)
        print("Dataframes saved successfully as 'train.csv' and 'test.csv'.")

    except FileNotFoundError:
        print(f"Error: The file '{dataset_name}' was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")


dataset_name = 'Churn.csv'
split_and_save_dataset(dataset_name)

Dataset loaded successfully with shape: (10000, 14)
Train set shape: (8000, 14), Test set shape: (2000, 14)
Dataframes saved successfully as 'train.csv' and 'test.csv'.

In [3]:
df = pd.read_csv('Churn.csv')
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')