In [2]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [5]:
df = pd.read_csv('../datasets/Titanic/train.csv')

In [8]:
df = df._get_numeric_data()

In [10]:
pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

     PassengerId  Survived    Pclass       Age     SibSp     Parch      Fare
0      -1.730108 -0.789272  0.827377 -0.530377  0.432793 -0.473674 -0.502445
1      -1.726220  1.266990 -1.566107  0.571831  0.432793 -0.473674  0.786845
2      -1.722332  1.266990  0.827377 -0.254825 -0.474545 -0.473674 -0.488854
3      -1.718444  1.266990 -1.566107  0.365167  0.432793 -0.473674  0.420730
4      -1.714556 -0.789272  0.827377  0.365167 -0.474545 -0.473674 -0.486337
..           ...       ...       ...       ...       ...       ...       ...
886     1.714556 -0.789272 -0.369365 -0.185937 -0.474545 -0.473674 -0.386671
887     1.718444  1.266990 -1.566107 -0.737041 -0.474545 -0.473674 -0.044381
888     1.722332 -0.789272  0.827377       NaN  0.432793  2.008933 -0.176263
889     1.726220  1.266990 -1.566107 -0.254825 -0.474545 -0.473674 -0.044381
890     1.730108 -0.789272  0.827377  0.158503 -0.474545 -0.473674 -0.492378

[891 rows x 7 columns]

In [11]:
cars = pd.read_csv('../datasets/Cars/train.csv')

In [12]:
cars.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [14]:
cars.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [1]:
d = {1:0.1, 2:33, 4:-0.5}

In [2]:
[k for k,v in d.items() if v > 0]

[1, 2]

In [4]:
# Example DataFrame
import pandas as pd
data = {
    'A': [1, 2, 3],
    'B': [1, 2, 3],  # This column is a duplicate of 'A'
    'C': [4, 5, 6],
    'D': [4, 5, 6]   # This column is a duplicate of 'C'
}

df = pd.DataFrame(data)

# Transpose the DataFrame, drop duplicates, then transpose it back to the original shape
df_cleaned = df.T.drop_duplicates().T

print(df_cleaned)

   A  C
0  1  4
1  2  5
2  3  6